# Generated by Django 4.0.4 on 2022-05-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustafa', '0003_student_about_student_avatar_student_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SP', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GRD', 'Graduate')], default='FR', max_length=3),
        ),
    ]
